allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
minimumReleaseAgeExclude:
  - '@angular-eslint/bundled-angular-compiler@22.1.0'
  - '@angular-eslint/eslint-plugin-template@22.1.0'
  - '@angular-eslint/eslint-plugin@22.1.0'
  - '@angular-eslint/schematics@22.1.0'
  - '@angular-eslint/template-parser@22.1.0'
  - '@angular-eslint/utils@22.1.0'
  - '@angular-eslint/builder@22.1.0'
  - angular-eslint@22.1.0
