import { FeeRequestRow } from './fee-request.models';

export const FEE_REQUEST_SAMPLE_DATA: FeeRequestRow[] = [
  {
    id: 1,
    code: 'SGC-2025-0001',
    date: '02/01/2025',
    entity: 'Banco',
    clientName: 'BCP S.A.',
    caseNumber: 'CJ-2025-0001',
    expenseType: 'Judicial',
    expenseName: 'Aranceles Judiciales',
    concept: 'Arancel de Demanda',
    amount: 320.0,
    currency: 'S/',
    state: 'Reembolsado',
    defendant: 'Rodríguez Fuentes María Elena',
    fileNumber: 'EXP-2025-0001',
    requesterName: 'B. Jiménez',
    isRefundable: 'Sí',
    history: [
      { action: 'Solicitud registrada', state: 'Registrado', date: '02/01/2025', time: '09:15', user: 'B. Jiménez' },
      { action: 'Pago registrado', state: 'Pagado', date: '05/01/2025', time: '11:30', user: 'B. Jiménez', observation: 'Recibo N° 2025-00041' },
      { action: 'Proceso concluido', state: 'Concluído', date: '20/03/2025', time: '16:00', user: 'B. Jiménez' },
      { action: 'Reembolso aprobado', state: 'Reembolsado', date: '28/03/2025', time: '10:45', user: 'S. Echavarría', observation: 'Transferencia interbancaria confirmada' },
    ],
  },
  {
    id: 2,
    code: 'SGC-2025-0002',
    date: '08/01/2025',
    entity: 'Banco',
    clientName: 'BBVA Perú',
    caseNumber: 'CJ-2025-0002',
    expenseType: 'Judicial',
    expenseName: 'Gastos Notariales',
    concept: 'Arancel de Apelación',
    amount: 215.5,
    currency: 'S/',
    state: 'Concluído',
    defendant: 'Torres Quispe Carlos Alberto',
    fileNumber: 'EXP-2025-0002',
    requesterName: 'B. Jiménez',
    isRefundable: 'Sí',
    history: [
      { action: 'Solicitud registrada', state: 'Registrado', date: '08/01/2025', time: '08:50', user: 'B. Jiménez' },
      { action: 'Pago registrado', state: 'Pagado', date: '10/01/2025', time: '09:20', user: 'B. Jiménez' },
      { action: 'Proceso concluido', state: 'Concluído', date: '14/04/2025', time: '14:30', user: 'B. Jiménez' },
    ],
  },
  {
    id: 3,
    code: 'SGC-2025-0003',
    date: '05/01/2025',
    entity: 'Empresa',
    clientName: 'Constructora Andina S.A.C.',
    caseNumber: 'CJ-2025-0003',
    expenseType: 'Administrativo',
    expenseName: 'Transporte y Movilidad',
    concept: 'Transporte y Movilidad',
    amount: 120.0,
    currency: 'S/',
    state: 'Concluído',
    requesterName: 'B. Jiménez',
    history: [
      { action: 'Solicitud registrada', state: 'Registrado', date: '05/01/2025', time: '08:30', user: 'B. Jiménez' },
      { action: 'Pago registrado', state: 'Pagado', date: '07/01/2025', time: '11:00', user: 'B. Jiménez', observation: 'Recibo N° 2025-00058' },
      { action: 'Caso concluido', state: 'Concluído', date: '20/02/2025', time: '16:30', user: 'B. Jiménez' },
    ],
  },
  {
    id: 4,
    code: 'SGC-2025-0004',
    date: '12/01/2025',
    entity: 'Empresa',
    clientName: 'Inmobiliaria del Norte S.A.C.',
    caseNumber: 'CJ-2025-0004',
    expenseType: 'Administrativo',
    expenseName: 'Comunicaciones y Courier',
    concept: 'Comunicaciones y Courier',
    amount: 85.0,
    currency: 'S/',
    state: 'Pagado',
    requesterName: 'B. Jiménez',
    history: [
      { action: 'Solicitud registrada', state: 'Registrado', date: '12/01/2025', time: '14:20', user: 'B. Jiménez' },
      { action: 'Pago registrado', state: 'Pagado', date: '14/01/2025', time: '09:45', user: 'B. Jiménez', observation: 'Recibo N° 2025-00072' },
    ],
  },
  {
    id: 5,
    code: 'SGC-2025-0009',
    date: '17/02/2025',
    entity: 'Persona Natural',
    clientName: 'Marco Antonio Villanueva Chávez',
    caseNumber: 'CJ-2025-0009',
    expenseType: 'Administrativo',
    expenseName: 'Depósito de Garantía',
    concept: 'Depósito de Garantía',
    amount: 200.0,
    currency: 'S/',
    state: 'Registrado',
    requesterName: 'B. Jiménez',
    history: [
      { action: 'Solicitud registrada', state: 'Registrado', date: '17/02/2025', time: '11:10', user: 'B. Jiménez' },
    ],
  },
  {
    id: 6,
    code: 'SGC-2025-0013',
    date: '10/01/2026',
    entity: 'Banco',
    clientName: 'BCP S.A.',
    caseNumber: 'C-2025-0314',
    expenseType: 'Judicial',
    expenseName: 'Aranceles Judiciales',
    concept: 'Arancel de Medida Cautelar',
    amount: 150.0,
    currency: 'S/',
    state: 'Pagado',
    defendant: 'Rodríguez Fuentes María Elena',
    fileNumber: 'FILE-2025-0087',
    requesterName: 'Administrador',
    isRefundable: 'Sí',
    finalDocumentName: 'documento-final-C-2025-0314.pdf',
    history: [
      { action: 'Solicitud registrada', state: 'Registrado', date: '10/01/2026', time: '09:00', user: 'Administrador' },
      { action: 'Pago registrado', state: 'Pagado', date: '12/01/2026', time: '10:30', user: 'Administrador', observation: 'Recibo N° 2026-00014' },
      { action: 'Documento final cargado', state: 'Pagado', date: '13/01/2026', time: '09:20', user: 'Administrador' },
    ],
  },
  {
    id: 7,
    code: 'SGC-2025-0014',
    date: '14/01/2026',
    entity: 'Banco',
    clientName: 'BCP S.A.',
    caseNumber: 'C-2025-0287',
    expenseType: 'Judicial',
    expenseName: 'Aranceles Judiciales',
    concept: 'Arancel de Ejecución de Sentencia',
    amount: 275.0,
    currency: 'S/',
    state: 'Pagado',
    defendant: 'Rodríguez Fuentes María Elena',
    fileNumber: 'FILE-2025-0061',
    requesterName: 'Administrador',
    isRefundable: 'Sí',
    history: [
      { action: 'Solicitud registrada', state: 'Registrado', date: '14/01/2026', time: '09:30', user: 'Administrador' },
      { action: 'Pago registrado', state: 'Pagado', date: '16/01/2026', time: '11:15', user: 'Administrador', observation: 'Recibo N° 2026-00022' },
    ],
  },
];
